# Change these first
owner: Kadantte # Your GitHub organization or username, where this repository lives
repo: candy-up # The name of this repository

sites:
  - name: Kadantte
    url: https://kadantte.moe
  - name: Why-inside.me
    url: https://s1.why-inside.me/u/y8A3ka.png
#  - name: LiDa <3
#    url: https://LiDa.kadantte.repl.co
#  - name: Lavalink
#    url: https://lidalavalink.kadantte.repl.co/metrics
  - name: Anime List
    url: https://list.kadantte.moe
  - name: Manga List
    url: https://list.kadantte.moe/?type=manga
  - name: AnimeChan
    url: https://anichan.kadantte.moe
 #  - name: nHentai API
 #    url: https://nh.usui.moe
 # - name: nHentai CDN
 #   url: https://nhcdn.ga
 # - name: nHentai CDN-EU
 #   url: https://eu.nhcdn.ga
 # - name: nHentai CDN-NA
 #   url: https://na.nhcdn.ga
 # - name: nHentai CDN-ASIA
 #   url: https://asia.nhcdn.ga
  - name: Li Da Server
    url: https://me.kadantte.moe
  - name: Ev-Supervision
    url: https://evsupervision.com/evsupervision/manager/signin

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.kadantte.moe
  # baseUrl: /your-repo-name
  logoUrl: https://kadantte.moe/assets/img/candy.png
  name: Candy Status
  introTitle: "**Candy Status**"
  introMessage: Status page which uses **real-time** data.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
